version: '3.8'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: prod
    networks:
      default:
        aliases:
          - www.symfony-bootstraped.test

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: babar
      POSTGRES_USER: test

  dockerize:
    image: jwilder/dockerize
